#!/usr/bin/env node
// Check that a NEXT_PUBLIC_MODEL_BASE actually serves the model weights.
//
//   node scripts/verify-models.mjs https://models.example.com/v1
//   node scripts/verify-models.mjs --write          # regenerate the manifest
//
// public/models/ is 4.9 GB and git-ignored, so it deploys nowhere. After
// uploading the weights, this says whether the upload is complete and usable —
// instead of finding out from an athlete whose analysis died.
//
// It checks the three things that actually break, without downloading 4.9 GB:
//   · presence      — a 404 on one file kills its whole device tier
//   · byte size     — a truncated multi-GB upload answers 200 with short content,
//                     and onnxruntime fails much later with an opaque error
//   · cache headers — these files are immutable, so they should be cached for a
//                     long time. Without it every analysis re-downloads gigabytes
//                     and the transfer bill scales with usage instead of users.
//   · CORS          — the browser fetches these cross-origin. No
//                     Access-Control-Allow-Origin and every model "is missing",
//                     which looks identical to a failed upload from the app side.

import { readFileSync, writeFileSync, statSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const MANIFEST = join(HERE, "models.manifest.json");
const LOCAL = join(HERE, "..", "public", "models");

// which files each device path fetches — see lib/pose2d-refine.ts and lib/ensemble.ts
const USED_BY = {
  "pose_landmarker_heavy.task": ["always"],
  "yolov8s.onnx": ["always"],
  "motionbert_3d_243.onnx": ["always"],
  "rtmpose_x.onnx": ["always"],
  "vitpose_l_fp32.onnx": ["webgpu-fast"],
  "vitpose_h_fp16.onnx": ["webgpu-best"],
  "vitpose_fp16.onnx": ["webgpu-fallback"],
  "vitpose_int8.onnx": ["no-webgpu"],
  "sapiens_03b_fp16.onnx": ["webgpu-fast"],
  "sapiens_06b_fp16.onnx": ["webgpu-best"],
  "pose_landmarker_full.task": ["unused"],
  "pose_landmarker_lite.task": ["unused"],
};

const mb = (b) => `${(b / 1024 / 1024).toFixed(0)} MB`;

if (process.argv[2] === "--write") {
  const files = readdirSync(LOCAL)
    .filter((f) => !f.startsWith("."))
    .map((name) => ({ name, bytes: statSync(join(LOCAL, name)).size, usedBy: USED_BY[name] ?? ["unknown"] }))
    .sort((a, b) => b.bytes - a.bytes);
  writeFileSync(MANIFEST, JSON.stringify({ _comment: "Generated by scripts/verify-models.mjs --write from public/models/. Byte sizes are the check: a truncated multi-GB upload is the common failure and Content-Length catches it without downloading.", files }, null, 2) + "\n");
  console.log(`wrote ${files.length} files, ${mb(files.reduce((s, f) => s + f.bytes, 0))} total`);
  process.exit(0);
}

const base = (process.argv[2] || process.env.NEXT_PUBLIC_MODEL_BASE || "").replace(/\/+$/, "");
if (!base || base.startsWith("/")) {
  console.error("Usage: node scripts/verify-models.mjs <https://base/url>   (or --write)");
  console.error("A relative base means the app reads public/models/, which does not deploy.");
  process.exit(2);
}

const { files } = JSON.parse(readFileSync(MANIFEST, "utf8"));
const needed = files.filter((f) => !f.usedBy.includes("unused"));
const skipped = files.filter((f) => f.usedBy.includes("unused"));

const rows = await Promise.all(needed.map(async (f) => {
  const url = `${base}/${f.name}`;
  try {
    // Origin makes the response reveal whether CORS is configured for a browser
    const r = await fetch(url, { method: "HEAD", headers: { Origin: "https://app.invalid" } });
    const len = Number(r.headers.get("content-length") ?? NaN);
    const cors = r.headers.get("access-control-allow-origin");
    const cache = r.headers.get("cache-control") ?? "";
    const maxAge = Number(/max-age=(\d+)/.exec(cache)?.[1] ?? 0);
    if (!r.ok) return { f, bad: `HTTP ${r.status}` };
    if (Number.isFinite(len) && len !== f.bytes) return { f, bad: `${mb(len)} served, expected ${mb(f.bytes)} — truncated upload` };
    // Only a warning: a base on the app's own origin needs no CORS header. From a
    // separate host it does, and without it the file is unreachable to a browser.
    if (!cors) return { f, len, warn: "no Access-Control-Allow-Origin (fine only if same-origin as the app)" };
    // a day is the floor worth accepting; these files never change
    if (maxAge < 86400) return { f, len, warn: `cache-control "${cache || "absent"}" — re-downloads instead of caching` };
    return { f, len, cors, maxAge };
  } catch (e) {
    return { f, bad: e.message };
  }
}));

const bad = rows.filter((r) => r.bad);
for (const r of rows.sort((a, b) => b.f.bytes - a.f.bytes)) {
  const tag = r.bad ? "FAIL" : r.warn ? "WARN" : "ok  ";
  console.log(`${tag}  ${r.f.name.padEnd(28)} ${mb(r.f.bytes).padStart(8)}  ${r.f.usedBy.join(",").padEnd(16)} ${r.bad ?? r.warn ?? ""}`);
}
if (skipped.length) {
  console.log(`\nnot needed (nothing loads them): ${skipped.map((f) => f.name).join(", ")}`);
}

// per-tier verdict: a tier is only usable if every file it reaches for is there
const present = new Set(rows.filter((r) => !r.bad).map((r) => r.f.name));
const tiers = {
  "no-webgpu": ["always", "no-webgpu"],
  "webgpu-fast (default)": ["always", "webgpu-fast"],
  "webgpu-best": ["always", "webgpu-best"],
};
console.log();
for (const [tier, tags] of Object.entries(tiers)) {
  const set = needed.filter((f) => f.usedBy.some((u) => tags.includes(u)));
  const missing = set.filter((f) => !present.has(f.name));
  const bytes = set.reduce((s, f) => s + f.bytes, 0);
  console.log(`${missing.length ? "FAIL" : "ok  "}  ${tier.padEnd(22)} ${mb(bytes).padStart(8)} first-run download${missing.length ? `  missing: ${missing.map((f) => f.name).join(", ")}` : ""}`);
}

const warned = rows.filter((r) => r.warn);
console.log(
  bad.length
    ? `\n${bad.length} of ${needed.length} files missing or truncated.`
    : warned.length
      ? `\nAll ${needed.length} files present at the right size, but ${warned.length} send no CORS header — check that only if this host differs from the app's origin.`
      : `\nAll ${needed.length} files serve correctly, cached for ${Math.round(Math.min(...rows.map((r) => r.maxAge)) / 86400)} days.`
);
process.exit(bad.length ? 1 : 0);
